
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace moxiCommunity.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BuySolution
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BuySolution()
    {

        this.SolutionGoods = new HashSet<SolutionGoods>();

    }


    public int ID { get; set; }

    public int topicID { get; set; }

    public int userID { get; set; }

    public int state { get; set; }

    public System.DateTime creatDate { get; set; }

    public string deleteBody { get; set; }



    public virtual Topic Topic { get; set; }

    public virtual CommunityUser CommunityUser { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SolutionGoods> SolutionGoods { get; set; }

}

}
