
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace moxiCommunity.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CommunityUser
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CommunityUser()
    {

        this.BuySolution = new HashSet<BuySolution>();

        this.Topic = new HashSet<Topic>();

        this.TopicReply = new HashSet<TopicReply>();

        this.ReplyAgree = new HashSet<ReplyAgree>();

    }


    public int ID { get; set; }

    public Nullable<int> moxiID { get; set; }

    public string Name { get; set; }

    public string UserLoginToken { get; set; }

    public System.DateTime joinDate { get; set; }

    public string avatar { get; set; }

    public int lv { get; set; }

    public string userName { get; set; }

    public string password { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BuySolution> BuySolution { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Topic> Topic { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TopicReply> TopicReply { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ReplyAgree> ReplyAgree { get; set; }

}

}
