
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace moxiCommunity.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ReplyAgree
{

    public int ID { get; set; }

    public int replyID { get; set; }

    public Nullable<int> userID { get; set; }

    public string IP { get; set; }

    public Nullable<bool> agree { get; set; }



    public virtual TopicReply TopicReply { get; set; }

    public virtual CommunityUser CommunityUser { get; set; }

}

}
