
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace moxiCommunity.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Topic
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Topic()
    {

        this.BuySolution = new HashSet<BuySolution>();

        this.TopicReply = new HashSet<TopicReply>();

    }


    public int ID { get; set; }

    public string title { get; set; }

    public string body { get; set; }

    public System.DateTime creatDate { get; set; }

    public int replys { get; set; }

    public Nullable<int> suggest { get; set; }

    public int node { get; set; }

    public int userID { get; set; }

    public int state { get; set; }



    public virtual BuyDemand BuyDemand { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BuySolution> BuySolution { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TopicReply> TopicReply { get; set; }

    public virtual CommunityUser CommunityUser { get; set; }

}

}
