
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace moxiCommunity.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TopicReply
{

    public int ID { get; set; }

    public int topicID { get; set; }

    public string body { get; set; }

    public int userID { get; set; }

    public System.DateTime creatDate { get; set; }

    public int floor { get; set; }

    public int state { get; set; }



    public virtual CommunityUser CommunityUser { get; set; }

    public virtual Topic Topic { get; set; }

}

}
